language: c
sudo: required
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libzip-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - ccache
      - mysql
      - bison
      - re2c
      - openssl
      - gmp


services:
  - mysql
  - postgresql

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - MYSQL_TEST_HOST=127.0.0.1
    - MYSQL_TEST_USER=travis
    - PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=test"
    - PDO_MYSQL_TEST_USER=travis
    - PDO_MYSQL_TEST_PASS=
    - PDO_MYSQL_TEST_HOST=127.0.0.1
    - REPORT_EXIT_STATUS=1

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - ENABLE_MAINTAINER_ZTS=0
        - ENABLE_DEBUG=0
    - os: linux
      dist: xenial
      env:
        - ENABLE_MAINTAINER_ZTS=1
        - ENABLE_DEBUG=1
    - os: osx
      osx_image: xcode10.1
      env:
        - ENABLE_MAINTAINER_ZTS=0
        - ENABLE_DEBUG=0

before_script:
    - ccache --version
    - ccache --zero-stats
    - export USE_CCACHE=1
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        . ./travis/setup_linux.sh
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        . ./travis/setup_osx.sh
      fi
    # Compile PHP
    - ./travis/compile.sh
    # Setup Extensions
    - . ./travis/ext/mysql/setup.sh
    - . ./travis/ext/mysqli/setup.sh
    - . ./travis/ext/pdo_mysql/setup.sh
    - . ./travis/ext/pgsql/setup.sh
    - . ./travis/ext/pdo_pgsql/setup.sh

# Run PHPs run-tests.php
script:
    - ./sapi/cli/php run-tests.php -p `pwd`/sapi/cli/php $(if [ $ENABLE_DEBUG == 0 ]; then echo "-d opcache.enable_cli=1 -d opcache.protect_memory=1 -d zend_extension=`pwd`/modules/opcache.so"; fi) -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --show-slow 1000 --set-timeout 120

after_success:
    - ccache --show-stats
