git:
  quiet: true

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0 ENABLE_OPCACHE=1
    - os: linux
      dist: xenial
      compiler: gcc
      env: ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0 ENABLE_OPCACHE=0
    - os: linux
      dist: xenial
      compiler: gcc
      env: ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1 ENABLE_OPCACHE=0
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0 ENABLE_OPCACHE=1
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1 ENABLE_OPCACHE=0
  allow_failures:
    - os: osx

language: c
sudo: required

addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libzip-dev
      - libsqlite3-dev
      - libwebp-dev
      - libonig-dev
  homebrew:
    packages:
      - ccache
      - bison
      - re2c
      - openssl
      - mysql
      - postgresql
      - enchant
      - freetype
      - gettext
      - intltool
      - icu4c
      - libedit
      - zlib
      - t1lib
      - gd

services:
  - mysql
  - postgresql

cache:
    ccache: true

env:
    global:
      - MYSQL_TEST_HOST=127.0.0.1
      - MYSQL_TEST_USER=root
      - PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=test"
      - PDO_MYSQL_TEST_USER=root
      - PDO_MYSQL_TEST_PASS=
      - PDO_MYSQL_TEST_HOST=127.0.0.1
      - REPORT_EXIT_STATUS=1

before_script:
    # Setup OS
    - . ./travis/os/$TRAVIS_OS_NAME.sh
    # Setup ccache
    - ccache --version
    - ccache --zero-stats
    - export USE_CCACHE=1
    # Compile PHP
    - ./travis/compile.sh
    # Setup Extensions
    - . ./travis/ext/mysql/setup.sh
    - . ./travis/ext/mysqli/setup.sh
    - . ./travis/ext/pdo_mysql/setup.sh
    - . ./travis/ext/pgsql/setup.sh
    - . ./travis/ext/pdo_pgsql/setup.sh

# Run PHPs run-tests.php
script:
    - ./sapi/cli/php run-tests.php -p `pwd`/sapi/cli/php $(if [ $ENABLE_DEBUG == 0 ]; then echo "-d opcache.enable_cli=1 -d opcache.protect_memory=1 -d zend_extension=`pwd`/modules/opcache.so"; fi) -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --show-slow 1000 --set-timeout 120

after_success:
    - ccache --show-stats
